import { invoke } from "./ui-context.js";

export const desktopApi = {
  ipcAddr: () => invoke("ipc_addr"),
  codexStatus: () => invoke("codex_status"),
  claudeStatus: () => invoke("claude_status"),
  openclawStatus: () => invoke("openclaw_status"),
  httpReceiverStatus: () => invoke("http_receiver_status"),
  platformCapabilities: () => invoke("platform_capabilities"),
  platformPaths: () => invoke("platform_paths"),
  getAppSettings: () => invoke("get_app_settings"),
  getAvailableDisplays: () => invoke("get_available_displays"),
  getSnapshot: () => invoke("get_snapshot"),
  getSnapshotStatusSurfaceBundle: () => invoke("get_snapshot_status_surface_bundle"),
  buildStatusSurfaceScene: () => invoke("build_status_surface_scene"),
  ingestSample: (fileName) => invoke("ingest_sample", { fileName }),
  approvePermission: (requestId) => invoke("approve_permission", { requestId }),
  denyPermission: (requestId) => invoke("deny_permission", { requestId }),
  answerQuestion: (requestId, answer) => invoke("answer_question", { requestId, answer }),
  skipQuestion: (requestId) => invoke("skip_question", { requestId }),
  setIslandPanelStagePassive: (height) => invoke("set_island_panel_stage_passive", { height }),
  setIslandBarStagePassive: () => invoke("set_island_bar_stage_passive"),
  setIslandExpandedPassive: (expanded) => invoke("set_island_expanded_passive", { expanded }),
  showMainWindowInteractive: () => invoke("show_main_window_interactive"),
  setIslandPanelStage: (height) => invoke("set_island_panel_stage", { height }),
  setIslandBarStage: () => invoke("set_island_bar_stage"),
  setIslandExpanded: (expanded) => invoke("set_island_expanded", { expanded }),
  setMacosSharedExpandedHeight: (height) => invoke("set_macos_shared_expanded_height", { height }),
  hideMainWindow: () => invoke("hide_main_window"),
  openSettingsLocation: () => invoke("open_settings_location"),
  openReleasePage: () => invoke("open_release_page"),
  setCompletionSoundEnabled: (enabled) => invoke("set_completion_sound_enabled", { enabled }),
  setMascotEnabled: (enabled) => invoke("set_mascot_enabled", { enabled }),
  setPreferredDisplayIndex: (index) => invoke("set_preferred_display_index", { index }),
  quitApplication: () => invoke("quit_application"),
  focusSessionTerminal: (sessionId) => invoke("focus_session_terminal", { sessionId }),
  bindSessionTerminal: (sessionId) => invoke("bind_session_terminal", { sessionId }),
};
